### ISSUE TITLE
How to compile with Windows?

### ISSUE THREAD

**Issue by David-OConnor** [fpgaminer/rust-lzma#20]
Error:
`thread 'main' panicked at 'Could not find liblzma using pkg-config',

I had to download a Ubuntu lzma package to make it work there. I downloaded a Windows bin - how do I make this compile?

**Comment by fpgaminer** [comment]
I have not tried to use this crate on Windows, so unfortunately I cannot be of help.  I would suggest using something like https://crates.io/crates/xz2 instead, since I believe that has Windows support.

**Comment by David-OConnor** [comment]
Thank you; got it working with that crate.
