### ISSUE TITLE
docs.rs documentation is not working

### ISSUE THREAD

**Issue by Taywee** [fpgaminer/rust-lzma#22]
For some reason, the current version of the documentation on docs.rs shows "rust-lzma-0.5.1 doesn't have any documentation."

https://docs.rs/crate/rust-lzma/0.5.1

**Comment by fpgaminer** [comment]
Thank you for letting me know!  Very odd.  Looks like the docs failed for 0.5.0 as well.  I will take a look when I get a chance.

**Comment by Caellian** [comment]
This is fixed now.

**Comment by fpgaminer** [comment]
Awesome. Thank you for letting me know.
