### ISSUE TITLE
Static linking support

### ISSUE THREAD

**Issue by ajeetdsouza** [fpgaminer/rust-lzma#28]
Hey, thanks for a fantastic crate! It would be great if you could support static linking - that way, we wouldn't have to rely on the host computer having `liblzma` installed.

**Comment by fpgaminer** [comment]
Thank you, but I'm sorry to say I'm not maintaining this repo at the moment.  There are better lzma Rust crates.

**Comment by crazystylus** [comment]
Hi @fpgaminer ,

**Comment by crazystylus** [comment]
Hi @fpgaminer ,
It's not valid to say other crates are better. I have some issues with basic xz extraction on other crates while I am getting no issues when using your crate. Please refer to these issues:
- https://github.com/alexcrichton/xz2-rs/issues/112
- https://github.com/gendx/lzma-rs/issues/97
- https://github.com/gendx/lzma-rs/issues/98

I have added support for static linking to your crate in [this fork](https://github.com/crazystylus/rust-lzma/tree/feat-static-linking). Would you accept a PR?

**Comment by fpgaminer** [comment]
> It's not valid to say other crates are better.

I mean, they're better because they're maintained... ostensibly, anyway.  Odd that your issue on xz2-rs hasn't been touched.

Sure, a PR would be welcome.  Please fix the typo(s) if you have a moment.

**Comment by ajeetdsouza** [comment]
> Odd that your issue on xz2-rs hasn't been touched.

Unfortunately, there are a lot of similar issues on `xz2`: https://github.com/alexcrichton/xz2-rs/issues/75#issuecomment-780776200

**Comment by fpgaminer** [comment]
Merged, and I've pushed a new version to crates.io.

**Comment by crazystylus** [comment]
> Merged, and I've pushed a new version to crates.io.

Thanks!!
